"""Provides ways of dealing with user input."""

from .keys import K_0, K_KP_1, K_1, K_KP_2, K_2, K_KP_3, K_3, K_KP_4, K_4, K_KP_5, K_5, K_KP_6, K_6, K_KP_7, K_7, K_KP_8, K_8, K_KP_9, K_9, K_KP_ADD, K_A, K_KP_DECIMAL, K_APOSTROPHE, K_KP_DIVIDE, K_B, K_KP_ENTER, K_BACKSLASH, K_KP_EQUAL, K_BACKSPACE, K_KP_MULTIPLY, K_C, K_KP_SUBTRACT, K_CAPS_LOCK, K_L, K_COMMA, K_LAST, K_D, K_LEFT, K_DELETE, K_LEFT_ALT, K_DOWN, K_LEFT_BRACKET, K_E, K_LEFT_CONTROL, K_END, K_LEFT_SHIFT, K_ENTER, K_LEFT_SUPER, K_EQUAL, K_M, K_ESCAPE, K_MENU, K_F, K_MINUS, K_F1, K_N, K_F10, K_NUM_LOCK, K_F11, K_O, K_F12, K_P, K_F13, K_PAGE_DOWN, K_F14, K_PAGE_UP, K_F15, K_PAUSE, K_F16, K_PERIOD, K_F17, K_PRINT_SCREEN, K_F18, K_Q, K_F19, K_R, K_F2, K_RIGHT, K_F20, K_RIGHT_ALT, K_F21, K_RIGHT_BRACKET, K_F22, K_RIGHT_CONTROL, K_F23, K_RIGHT_SHIFT, K_F24, K_RIGHT_SUPER, K_F25, K_S, K_F3, K_SCROLL_LOCK, K_F4, K_SEMICOLON, K_F5, K_SLASH, K_F6, K_SPACE, K_F7, K_T, K_F8, K_TAB, K_F9, K_U, K_G, K_UNKNOWN, K_GRAVE_ACCENT, K_UP, K_H, K_V, K_HOME, K_W, K_I, K_WORLD_1, K_INSERT, K_WORLD_2, K_J, K_X, K_K, K_Y, K_KP_0, K_Z

from .actions import A_PRESS, A_RELEASE, A_REPEAT

from .controller import io_controller, keycontrol, mousecontrol, empty_function
